version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-demo
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5

  order-service:
    build: 
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - ORDER_NOTIFICATIONS_QUEUE=order_notifications
    depends_on:
      rabbitmq:
        condition: service_healthy

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - ORDER_NOTIFICATIONS_QUEUE=order_notifications
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data: 